### ISSUE TITLE
wallet wont sync

### ISSUE THREAD

**Issue by etherbinge** [MintcoinCommunity/Mintcoin-Desktop-Wallet#22] opened 2016-10-22 21:55 UTC
upgraded mintcoin wallet still saying out of sync please help i have sent a lot of mintcoin to this wallet

**Comment by Fuzzbawls** [comment] 2016-10-22 21:56
please provide some details

**Comment by etherbinge** [comment] 2016-10-22 21:57
i have just installed the new wallet sent what I have from poloniex because they are not supporting it I assumed my wallet would just sync but it is reading out of sync in red and I am not quite sure how to get it too sync any more info needed ?

**Comment by etherbinge** [comment] 2016-10-22 21:58
running windows

**Comment by Fuzzbawls** [comment] 2016-10-22 22:00
What Version?
How many connections?
Is this a completely fresh install or an upgrade?
If upgrading, from what version?
Are you trying to sync from the network or using a bootstrap?

**Comment by etherbinge** [comment] 2016-10-22 22:02
v2.0.2.0
0 active connections saying wallet is offline 
fresh install
no bootstrap

**Comment by Fuzzbawls** [comment] 2016-10-22 22:08
Either your computer cannot resolve the DNS hostname to fetch initial peers, or you have a firewall blocking the program (or both)

post your debug.log file's contents. The file can be found at the following location:
C:\Documents and Settings\YourUserName\Application data\MintCoin (XP)
C:\Users\YourUserName\Appdata\Roaming\MintCoin (Vista and 7)

**Comment by etherbinge** [comment] 2016-10-22 22:19
I  am running windows 10

**Comment by Fuzzbawls** [comment] 2016-10-22 22:21
same place as the Vista and Windows 7 location

**Comment by Fuzzbawls** [comment] 2016-12-01 02:28
Marking this as closed due to no more information having been submitted. If the problem is persisting, please comment again

**Closed by Fuzzbawls** 2016-12-01 02:28 UTC
Labels: help wanted

**Comment by sunsetjunks** [comment] 2018-01-18 19:07
How about settings for Mac?

**Comment by SKBMB** [comment] 2018-01-24 22:10
Hello, i just experienced the same issue on windows 10. 
Mintcoin wallet is not connecting and so not synchronizing. It's version 2.0.2.0 and QT 5.4.2 in case that's relevant as well.

I can provide an error log if that's required. Thanks a lot !
